version: '3'
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: registercontainer
      image: register 
      ports:
        - 8000:8000
      volumes:
        - .:/data