name: Internship Pro
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo Source Code
        uses: actions/checkout@v3
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          # Configure Apache as per your project requirements
      - name: Create project directory
        run: sudo mkdir -p /home/dell/devOps/django_ec2/s3pro
      - name: Copy project files to Apache document root
        run: |
          sudo cp -r * /home/dell/devOps/django_ec2/s3pro  # Replace with the appropriate path to your project files
      - name: Restart Apache
        run: sudo systemctl restart apache2
      - name: Configure Apache Server
        run: |
            sudo rm /etc/apache2/sites-available/000-default.conf
            sudo cp /home/dell/devOps/django_ec2/s3pro/apache/prod.conf /etc/apache2/sites-available/
            sudo cat /etc/apache2/sites-available/local.conf 
            sudo service apache2 reload 
            sudo a2ensite local.conf